#!./env/bin/python

from random import randrange
from shutil import get_terminal_size
from modules.boid import Boid
from modules.window import Window

term = get_terminal_size((80, 20))
window = Window(term.lines, term.columns)
boids = []
go_on = True
target = [0, 0]

def init():
    for i in range(randrange(window.x)):
        randx = randrange(window.x)
        randy = randrange(window.y)
        boids.append(Boid(randx, randy))
    return

def rule1():
    """
    Rule1 : Boids try to fly towards the centre of mass of neighbouring boids
    """
    # First we calculate the centre of mass of the boids and store it inside target
    total = [0, 0]
    for boid in boids:
        total[0] += boid.x
        total[1] += boid.y
    target[0] = total[0] // len(boids)
    target[1] = total[1] // len(boids)
    # Then we move the boids towards this point
    for boid in boids:
        boid.towards(target[0], target[1])
    return

def move():
    rule1()
    return

def render():
    for boid in boids:
        window.set(boid.x, boid.y, boid.char)
    window.set(target[0], target[1], 'T')
    window.display()
    window.flush()

def main():
    init()
    while go_on:
        move()
        render()

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt as e:
        print("\nBye !")
